environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.6.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build: false

test_script:
  - gradlew test

after_test:
  - gradlew jacocoTestReport
  - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "build\\reports\\jacoco\\test\\jacocoTestReport.xml"