environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

test_script:
  - gradlew test

